name: Publish release

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select environment
        required: true
        options:
          - CENTRAL
          - STAGE CENTRAL
          - DEV CENTRAL

jobs:
  publish-release:
    runs-on: ubuntu-latest
    #if: github.repository_owner == 'ballerina-platform'
    steps:
      - uses: actions/checkout@v2
      - name: Ballerina Build
        uses: ballerina-platform/ballerina-action/@master
        with:
          args:
            build
      - name: Ballerina Pack
        uses: ballerina-platform/ballerina-action/@master
        with:
          args:
            pack
      - name: Ballerina Dev Central Push
        if: ${{ github.event.inputs.environment }} = 'DEV CENTRAL'
        uses: ballerina-platform/ballerina-action/@master
        env:
          BALLERINA_DEV_CENTRAL: true
          BALLERINA_CENTRAL_ACCESS_TOKEN: ${{ secrets.BALLERINA_CENTRAL_DEV_ACCESS_TOKEN }}
        with:
          args:
            push
